## Минаков Артём, ПМ19-3, Билет 12

In [33]:
import numpy as np
from scipy.optimize import minimize
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression

In [48]:
a, b = np.random.randint(-10,10,5), 2
X = np.random.randn(40,5)
y = np.logical_and(X @ a + b > 0, 1).astype(int)

In [59]:
a,b

(array([-7,  9,  4,  9, -8]), 2)

In [49]:
X

array([[-0.26237712,  0.63184658, -0.59923667, -0.32532093,  1.38244992],
       [-0.90628958,  1.23164151,  0.30100515,  0.08903533, -2.1786258 ],
       [ 0.64117952, -0.27618626,  0.61491996, -2.19291889, -0.58293356],
       [-1.19953456,  1.3176275 ,  0.35311586,  0.79301484, -1.23731616],
       [-0.57819828, -1.14257387, -1.54032082,  0.50441213,  0.73532048],
       [-0.51419082,  0.86661349, -2.45014834,  0.12353995, -0.78684247],
       [-0.54035024,  0.14298795, -0.76932284,  1.1751044 , -0.31386997],
       [-0.23708942, -1.36418641,  0.81069953, -0.40673598,  1.11457223],
       [ 0.86115834,  0.61479162,  0.58981177, -0.27267301, -0.31447485],
       [-0.49434556, -2.68103029, -1.41170543, -0.45848428, -0.29611573],
       [-0.07456433, -0.24810958, -0.94972406, -0.23324928, -1.19102445],
       [-1.10540365, -0.58587672, -1.1297553 , -1.17300112, -0.38052887],
       [ 0.8336695 , -1.19532385, -1.49197708, -1.67665598, -0.31521154],
       [ 0.58266421, -0.22706907, -1.1

In [50]:
y

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1])

In [51]:
# МНК

def MLS_lin_reg(beta,args): #функция которая воспроизводит МНК для нашей функции
    #ее же мы будем оптимизировать методом BFGS
    x,y = args[0],args[1]
    return np.sum((y - np.sum(np.hstack((np.ones([x.shape[0],1]),x)) * beta,axis = 1))**2)

def MLS_lin_reg_gradient(beta,args): #градиент для функции выше
    x,y = args[0],args[1]
    gradient = np.zeros(len(beta))
    gradient[0] = -2*np.sum(y - np.sum(np.hstack((np.ones([x.shape[0],1]),x)) * beta,axis = 1))
    for i in range(x.shape[1]):
        gradient[i+1] = -2*np.sum((y - np.sum(np.hstack((np.ones([x.shape[0],1]),x)) * beta,axis = 1))*x[:,i])

    return gradient
   
        

In [52]:
beta = np.array([0,0,0,0,0,0]) #первый элемент в списке это b, так как я добавляю вектор с единицами в начало
res = minimize(MLS_lin_reg, x0 = beta, method='BFGS',
               jac=MLS_lin_reg_gradient, args= [X,y],
               options={'disp': True,'gtol': 1e-6})

Optimization terminated successfully.
         Current function value: 2.317879
         Iterations: 11
         Function evaluations: 16
         Gradient evaluations: 16


In [53]:
res.x #наши параметры, первый b, потом вектор а

array([ 0.54335601, -0.06427243,  0.24008317,  0.02521232,  0.22659283,
       -0.1843206 ])

In [54]:
#вектор реальных коэффициентов
beta_real = np.array([b] + a.tolist())
beta_real

array([ 2, -7,  9,  4,  9, -8])

In [55]:
#разница между реальным и полученным вектором коэффициентов
(res.x - beta_real)

array([-1.45664399,  6.93572757, -8.75991683, -3.97478768, -8.77340717,
        7.8156794 ])

In [56]:
#сравним значение MLS для коэффициентов полученных и реальных
print('MLS для настоящих коэффициентов =',MLS_lin_reg(beta_real,[X,y]))

print('MLS для наших коэффициентов =',MLS_lin_reg(res.x ,[X,y]))


MLS для настоящих коэффициентов = 14708.623285675418
MLS для наших коэффициентов = 2.3178786658897668


In [57]:
#теперь все это загоним в функцию
def solve(x,y):
    beta = np.zeros(X.shape[1]+1)
    res = minimize(MLS_lin_reg, x0 = beta, method='BFGS',
               jac=MLS_lin_reg_gradient, args= [X,y],
               
               options={'disp': True,'gtol': 1e-6})
    b = res.x[0]
    a = res.x[1:]
    return a,b

In [58]:
solve(X,y)

Optimization terminated successfully.
         Current function value: 2.317879
         Iterations: 11
         Function evaluations: 16
         Gradient evaluations: 16


(array([-0.06427243,  0.24008317,  0.02521232,  0.22659283, -0.1843206 ]),
 0.5433560089616464)